---
- hosts: all
  gather_facts: true
  become: true
  become_user: root
  tasks:
  - name: Add epel-release repo
    yum:
      name: epel-release
      state: present

  - name: Install nginx
    yum:
      name: nginx
      state: present # installs the Nginx.service
      
  - name: Start NGiNX
    service:
      name: nginx
      state: started  # starts the Nginx.boot
      
  - name: start nginx on boot
    service: name=nginx state=started enabled=yes
