---
- hosts: all
  gather_facts: true
  become: true
  become_user: root
  tasks:
  - name: Add epel-release repo
    yum:
      name: epel-release
      state: present

  - name: Install nginx
    yum:
      name: nginx
      state: present
